PracticalHTML5/Controllers/StatsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using PracticalHTML5.Indexes;

namespace PracticalHTML5.Controllers
{
    public class StatsController : RavenController
    {
        //private const string _viewName = "Index";
        private const string _viewName = "StoredIndex";

        public ActionResult Index()
        {
            return View(_viewName);
        }

        public ActionResult Data()
        {
            Response.Cache.SetMaxAge(TimeSpan.Zero);
            var query = DB.Query<PlayerStatisticsIndexCreationTask.Result, PlayerStatisticsIndexCreationTask>();

            return Json(query.ToList(), JsonRequestBehavior.AllowGet);
        }


    }
}

PracticalHTML5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Tic Tac Toe</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")


        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Tic Tac Toe", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Scoreboard", "Index", "Stats")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - ABL - The Problem Solver</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jquerycookie")

    <!--[if lt IE 8]>
        <script src="~/Scripts/json2.min.js"></script>
    <![endif]-->
        @RenderSection("scripts", required: false)
    </body>
</html>